version: '3.8'

services:
  # 데이터베이스 서버
  postgres:
    image: postgres:15-alpine
    container_name: commerceweb-postgres
    environment:
      POSTGRES_DB: commerceweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 56678
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # 데이터 저장소
  redis:
    image: redis:7-alpine
    container_name: commerceweb-redis
    ports:
      - "6379:6379"

  # 백엔드 서버
  backend:
    build:
      context: ./backend/api-server
      dockerfile: Dockerfile
    container_name: commerceweb-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/commerceweb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 56678
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      # 자바 코드의 ${jwt.secret}과 ${jwt.expiration}에 매핑됩니다.
      JWT_SECRET: "my_custom_secret_key_for_commerce_web_project_123456"
      JWT_EXPIRATION: 86400000
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

  # 프론트엔드 서버
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: commerceweb-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres-data: